language: node_js
node_js:
  - "10"

before_script:
  - "npm install"

script:
  - "npm run build"

deploy:
  skip_cleanup: true
  provider: surge
  project: ./public/
  domain: frontdevrocks.surge.sh
  on:
    branch: master